# Generated by Django 3.2.5 on 2021-07-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecentBlog',
            new_name='Blog',
        ),
    ]
