# Generated by Django 3.2.2 on 2021-07-26 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('heading_en', models.CharField(max_length=200, null=True)),
                ('heading_uz', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, null=True)),
                ('food_name_en', models.CharField(max_length=100, null=True)),
                ('food_name_uz', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(default=None, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('food_image', models.ImageField(blank=True, upload_to='images/restaurant/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=155, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('profile_pic', models.ImageField(blank=True, default='images/user.png', upload_to='images/users_images')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/instagram')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('description_en', models.CharField(max_length=100, null=True)),
                ('description_uz', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='images/user.png', upload_to='images/testimonials')),
                ('comment', models.TextField()),
                ('comment_en', models.TextField(null=True)),
                ('comment_uz', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, upload_to='images/room_images')),
                ('image_2', models.ImageField(blank=True, upload_to='images/room_images')),
                ('image_3', models.ImageField(blank=True, upload_to='images/room_images')),
                ('room_size', models.IntegerField()),
                ('room_number', models.IntegerField(unique=True)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not-available', 'Not-available')], default='Not-Available', max_length=100)),
                ('explanation', models.TextField()),
                ('explanation_en', models.TextField(null=True)),
                ('explanation_uz', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_category', to='user.roomcategory')),
                ('view', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_view', to='user.roomview')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.CharField(max_length=25, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Payment process...', 'Payment process...'), ('Paid', 'Paid')], default='Payment process...', max_length=100)),
                ('status_en', models.CharField(choices=[('Payment process...', 'Payment process...'), ('Paid', 'Paid')], default='Payment process...', max_length=100, null=True)),
                ('status_uz', models.CharField(choices=[('Payment process...', 'Payment process...'), ('Paid', 'Paid')], default='Payment process...', max_length=100, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.guest')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.room')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('room_price', models.FloatField(default=0)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.guest')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100, null=True)),
                ('facility_name_en', models.CharField(max_length=100, null=True)),
                ('facility_name_uz', models.CharField(max_length=100, null=True)),
                ('room', models.ManyToManyField(blank=True, to='user.Room')),
            ],
        ),
    ]
