# Generated by Django 3.2.2 on 2021-07-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
