# Generated by Django 3.2.5 on 2021-07-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_finance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityproperty',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='facility',
            field=models.ManyToManyField(to='user.FacilityProperty'),
        ),
    ]
