# Generated by Django 3.2.5 on 2021-07-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210726_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='HotelAmenities',
        ),
        migrations.RenameModel(
            old_name='FacilityProperty',
            new_name='RoomFacilities',
        ),
    ]
