# Generated by Django 3.2.5 on 2021-07-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.guest'),
        ),
    ]
